## Call Expressions

In [30]:
abs(-12)

12

In [31]:
round(5 - 1.3)

4

In [32]:
max(2, 2 + 3, 4)

5

In [37]:
import math
math.sqrt(9)

3.0

In [39]:
9 ** 0.5

3.0

In [41]:
(3 ** 2 + 4 ** 2) ** 0.5

5.0

In [43]:
math.sqrt(3 ** 2 + 4 ** 2)

5.0

In [45]:
math.sin(math.pi / 2)

1.0

## Strings

In [46]:
"data" + "8"

'data8'

In [52]:
'it's an error'

SyntaxError: invalid syntax (<ipython-input-52-67432722df07>, line 1)

In [76]:
"it's ok"

"it's ok"

In [77]:
'data'.count('a')

2

## Types

In [53]:
type(3)

int

In [54]:
type(3.0)

float

In [56]:
type("three")

str

In [61]:
type("3")

str

In [62]:
3 + 3

6

In [59]:
3 + "3"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [60]:
"3" + "3"

'33'

In [64]:
three = "3"
three + three

'33'

In [65]:
3 + int(three)

6

In [72]:
float('3.2') + int('4')

7.2

In [74]:
3 > 2

True

In [75]:
type(3 > 2)

bool

## Arrays

In [78]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [79]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [82]:
len(highs)

4

In [83]:
highs.size

4

In [87]:
highs.repeat(2)

array([ 13.6  ,  13.6  ,  14.387,  14.387,  14.585,  14.585,  15.164,
        15.164])

In [88]:
highs.sum()

57.736000000000004

In [89]:
highs.sum() / highs.size

14.434000000000001

In [90]:
highs.mean()

14.434000000000001

## Array Arithmetic

In [91]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, 
                  baseline_low - 0.629,
                  baseline_low - 0.126, 
                  baseline_low + 0.728)
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [92]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([ 11.472,  12.016,  11.711,  11.436])

In [93]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

In [95]:
(9/5*highs + 32 - (9/5*lows + 32))

array([ 20.6496,  21.6288,  21.0798,  20.5848])

In [96]:
9/5 * (highs - lows)

array([ 20.6496,  21.6288,  21.0798,  20.5848])

## Array functions

In [15]:
temps = make_array(
0.209,
0.253,
0.035,
0.226,
0.062,
0.045,
0.092,
0.231,
0.279,
0.158,
0.346,
0.332,
0.155,
0.184,
0.238,
0.385,
0.284,
0.427,
0.576,
0.344,
0.358,
0.500,
0.581,
0.568,
0.468,
0.652,
0.600,
0.604,
0.469,
0.587,
0.652,
0.535,
0.564,
0.587,
0.652,
0.791,
0.938
)

temps

In [16]:
temps

array([ 0.209,  0.253,  0.035,  0.226,  0.062,  0.045,  0.092,  0.231,
        0.279,  0.158,  0.346,  0.332,  0.155,  0.184,  0.238,  0.385,
        0.284,  0.427,  0.576,  0.344,  0.358,  0.5  ,  0.581,  0.568,
        0.468,  0.652,  0.6  ,  0.604,  0.469,  0.587,  0.652,  0.535,
        0.564,  0.587,  0.652,  0.791,  0.938])

In [98]:
max(temps)

0.93799999999999994

In [99]:
import numpy as np

In [101]:
np.sqrt(temps)

array([ 0.45716518,  0.50299105,  0.18708287,  0.47539457,  0.24899799,
        0.21213203,  0.30331502,  0.48062459,  0.52820451,  0.39749214,
        0.58821765,  0.57619441,  0.39370039,  0.42895221,  0.48785244,
        0.62048368,  0.5329165 ,  0.65345237,  0.75894664,  0.58651513,
        0.59833101,  0.70710678,  0.76223356,  0.75365775,  0.68410526,
        0.80746517,  0.77459667,  0.77717437,  0.68483575,  0.76615925,
        0.80746517,  0.73143694,  0.75099933,  0.76615925,  0.80746517,
        0.88938181,  0.968504  ])

In [102]:
np.sort(temps)

array([ 0.035,  0.045,  0.062,  0.092,  0.155,  0.158,  0.184,  0.209,
        0.226,  0.231,  0.238,  0.253,  0.279,  0.284,  0.332,  0.344,
        0.346,  0.358,  0.385,  0.427,  0.468,  0.469,  0.5  ,  0.535,
        0.564,  0.568,  0.576,  0.581,  0.587,  0.587,  0.6  ,  0.604,
        0.652,  0.652,  0.652,  0.791,  0.938])

In [103]:
np.diff(temps)

array([ 0.044, -0.218,  0.191, -0.164, -0.017,  0.047,  0.139,  0.048,
       -0.121,  0.188, -0.014, -0.177,  0.029,  0.054,  0.147, -0.101,
        0.143,  0.149, -0.232,  0.014,  0.142,  0.081, -0.013, -0.1  ,
        0.184, -0.052,  0.004, -0.135,  0.118,  0.065, -0.117,  0.029,
        0.023,  0.065,  0.139,  0.147])

In [104]:
np.sort(np.diff(temps))

array([-0.232, -0.218, -0.177, -0.164, -0.135, -0.121, -0.117, -0.101,
       -0.1  , -0.052, -0.017, -0.014, -0.013,  0.004,  0.014,  0.023,
        0.029,  0.029,  0.044,  0.047,  0.048,  0.054,  0.065,  0.065,
        0.081,  0.118,  0.139,  0.139,  0.142,  0.143,  0.147,  0.147,
        0.149,  0.184,  0.188,  0.191])

In [105]:
np.diff(temps) > 0

array([ True, False,  True, False, False,  True,  True,  True, False,
        True, False, False,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True], dtype=bool)

## Ranges

In [106]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [107]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [108]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [109]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

$$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$$

In [123]:
a = np.arange(1, 12, 4)

In [124]:
a

array([1, 5, 9])

In [125]:
a + 2

array([ 3,  7, 11])

In [126]:
4 * sum(1/a - 1/(a+2))

2.9760461760461765