## Call Expressions

In [95]:
abs(-12)

12

In [96]:
round(5 - 1.3)

4

In [97]:
round(3.4)

3

In [98]:
round(3.89)

4

In [99]:
max(2, 3 + 4, 5)

7

In [100]:
import math

In [101]:
math.sqrt(9)

3.0

In [102]:
9 ** 0.5

3.0

In [103]:
math.sin(math.pi / 2)

1.0

In [104]:
math.log?

In [105]:
math.log(1000)

6.907755278982137

In [106]:
math.pow(math.e, math.log(1000))

999.9999999999994

In [107]:
math.log(1024, 2)

10.0

In [108]:
2 ** 10

1024

## Strings

In [109]:
'data'

'data'

In [110]:
"data"

'data'

In [111]:
'data' + '8'

'data8'

In [112]:
'it's an error'

SyntaxError: invalid syntax (<ipython-input-112-67432722df07>, line 1)

In [113]:
"it's ok now"

"it's ok now"

## Types

In [114]:
3

3

In [115]:
3.0

3.0

In [116]:
type(3)

int

In [117]:
type(3.0)

float

In [118]:
type('three')

str

In [119]:
type('3')

str

In [120]:
'3' + '3'

'33'

In [121]:
3 + 3

6

In [122]:
3 + '3'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [124]:
int('3') + 4

7

In [125]:
'3' + '3'

'33'

In [126]:
'three' + 'three'

'threethree'

In [127]:
int('3' + '4') + 5

39

In [128]:
'3' + '4'

'34'

In [129]:
int('3' + '4')

34

In [130]:
34 + 5

39

In [131]:
1 + 2.3

3.3

In [132]:
greeting = 'hey'
name = 'you'
greeting + ', ' + name

'hey, you'

In [133]:
x = 3
y = 2
x > y

True

In [134]:
type(x > y)

bool

In [137]:
round(float('45.6'))

46

In [139]:
int('45')

45

In [140]:
int(45.6)

45

In [141]:
int('45.6')

ValueError: invalid literal for int() with base 10: '45.6'

## Arrays

In [2]:
from datascience import *

In [3]:
baseline_high = 14.48
highs = make_array(
    baseline_high - 0.880, # 1850
    baseline_high - 0.629, # 1900
    baseline_high - 0.126, # 1950
    baseline_high + 0.728  # 2000
)

In [4]:
highs

array([ 13.6  ,  13.851,  14.354,  15.208])

In [6]:
(9/5) * highs.item(0) + 32

56.480000000000004

In [7]:
(9/5) * highs.item(1) + 32

56.9318

In [8]:
(9/5) * highs + 32

array([ 56.48  ,  56.9318,  57.8372,  59.3744])

In [9]:
highs

array([ 13.6  ,  13.851,  14.354,  15.208])

In [10]:
highs + 1

array([ 14.6  ,  14.851,  15.354,  16.208])

In [11]:
highs.item(2)

14.354000000000001

In [12]:
highs.sum()

57.012999999999998

In [13]:
highs.mean()

14.25325

In [14]:
'data'.count('a')

2

In [15]:
highs

array([ 13.6  ,  13.851,  14.354,  15.208])

In [16]:
# Global low daily land temperature
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, # 1850
                  baseline_low - 0.629, # 1900
                  baseline_low - 0.126, # 1950
                  baseline_low + 0.728  # 2000
                  )
lows


array([ 2.128,  2.371,  2.874,  3.728])

In [17]:
highs

array([ 13.6  ,  13.851,  14.354,  15.208])

In [18]:
highs - lows

array([ 11.472,  11.48 ,  11.48 ,  11.48 ])

In [19]:
((9/5)*highs + 32) - ((9/5)*lows + 32)

array([ 20.6496,  20.664 ,  20.664 ,  20.664 ])

In [20]:
9/5 * (highs - lows)

array([ 20.6496,  20.664 ,  20.664 ,  20.664 ])

## Ranges

In [22]:
import numpy as np

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [25]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

$$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$$

In [33]:
a = np.arange(1, 100000, 4)

In [29]:
1/a

array([ 1.        ,  0.2       ,  0.11111111])

In [31]:
1/(a+2)

array([ 0.33333333,  0.14285714,  0.09090909])

In [34]:
4 * (1/a - 1/(a+2)).sum()

3.1415726535897965

In [39]:
4 * (1/a - 1/(a+2)).sum()

3.1415726535897965

In [40]:
!pip install datascience