## Growth Review

In [9]:
fed_budget_2002 = 2370000000000
fed_budget_2012 = 3380000000000
g = (fed_budget_2012 / fed_budget_2002) ** (1/10) - 1
g

0.03613617208346853

In [10]:
x = 2.37 

In [11]:
x = (1 + g) * x
x

2.4556427278378203

In [12]:
t = 5730
0.5 ** (1/t) - 1

-0.00012096077799361726

## Strings

In [15]:
'2.3'

'2.3'

In [16]:
'2.3' + 4

TypeError: Can't convert 'int' object to str implicitly

In [17]:
'2.3' * 4

'2.32.32.32.3'

In [18]:
float('2.3')

2.3

In [19]:
int('2.3')

ValueError: invalid literal for int() with base 10: '2.3'

In [20]:
int('23') + float('2.3')

25.3

In [21]:
x = 12
int(str(x) + '0')

120

## Sequences

In [22]:
baseline_high = 14.48
highs_list = [baseline_high - 0.880, baseline_high - 0.093,
              baseline_high + 0.105, baseline_high + 0.684]
highs_list

[13.6, 14.387, 14.585, 15.164]

In [23]:
sum(highs_list)/len(highs_list)

14.434000000000001

In [24]:
baseline_low = 3.00
lows_tuple = (baseline_low - 0.872, baseline_low - 0.629,
              baseline_low - 0.126, baseline_low + 0.728)
lows_tuple

(2.128, 2.371, 2.874, 3.7279999999999998)

## Arrays

In [25]:
import numpy as np

In [26]:
highs = np.array(highs_list)

In [27]:
lows = np.array((baseline_low - 0.872, baseline_low - 0.629,
                 baseline_low - 0.126, baseline_low + 0.728))

In [28]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [29]:
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [30]:
print(highs)

[ 13.6    14.387  14.585  15.164]


In [31]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [32]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

In [33]:
(9/5) * (highs - lows) + 32

array([ 52.6496,  53.6288,  53.0798,  52.5848])

In [52]:
len(highs)

4

In [53]:
highs.size

4

In [37]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [38]:
highs.item(0)

13.6

In [39]:
highs.item(1)

14.387

In [40]:
highs.item(-1)

15.164

In [41]:
highs.item(1) - highs.item(0)

0.7870000000000008

In [42]:
np.diff(highs)

array([ 0.787,  0.198,  0.579])

## Ranges

In [55]:
by_four = np.arange(1, 10, 4)
by_four

array([1, 5, 9])

In [44]:
4 * sum( 1/by_four - 1/(by_four + 2) )

3.1415906535898936

### Birthday problem

In [45]:
all_different = (364/365)*(363/365)*(362/365)

In [57]:
k = 4
numerators = np.arange(364, 365-k, -1)
numerators

array([364, 363, 362])

In [58]:
np.prod(numerators/365)

0.98364408753344978

In [59]:
k = 40
numerators = np.arange(364, 365-k, -1)
np.prod(numerators/365)

0.10876819018205097

In [50]:
ten = np.arange(1, 9)
np.cumprod(ten)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])

In [64]:
k = 60
numerators = np.arange(364, 365-k, -1)
np.cumprod(numerators/365)

array([ 0.99726027,  0.99179583,  0.98364409,  0.97286443,  0.95953752,
        0.9437643 ,  0.92566471,  0.90537617,  0.88305182,  0.85885862,
        0.83297521,  0.80558972,  0.77689749,  0.74709868,  0.71639599,
        0.68499233,  0.65308858,  0.62088147,  0.58856162,  0.55631166,
        0.52430469,  0.49270277,  0.46165574,  0.4313003 ,  0.40175918,
        0.37314072,  0.34553853,  0.31903146,  0.29368376,  0.26954537,
        0.24665247,  0.22502815,  0.20468314,  0.18561676,  0.16781789,
        0.15126599,  0.13593218,  0.12178034,  0.10876819,  0.09684839,
        0.08596953,  0.07607714,  0.06711463,  0.0590241 ,  0.05174716,
        0.0452256 ,  0.03940203,  0.03422039,  0.02962642,  0.02556801,
        0.02199549,  0.01886189,  0.01612304,  0.01373771,  0.01166765,
        0.00987754,  0.00833502,  0.00701055,  0.00587734])