## Growth Review

In [3]:
fed_budget_2002 = 2370000000000
fed_budget_2012 = 3380000000000
r = (fed_budget_2012 / fed_budget_2002) ** (1/10) - 1
r

0.03613617208346853

In [2]:
x = 2.37 

In [4]:
x = (1 + r) * x
x

2.4556427278378203

In [5]:
t = 5730
0.5 ** (1/t) - 1

-0.00012096077799361726

## Strings

In [152]:
"Hello"

'Hello'

In [153]:
'Hello'

'Hello'

In [154]:
'2.3'

'2.3'

In [155]:
'2.3' + 4

TypeError: Can't convert 'int' object to str implicitly

In [157]:
'2.3' * 4

'2.32.32.32.3'

In [158]:
float('2.3')

2.3

In [159]:
int('2.3')

ValueError: invalid literal for int() with base 10: '2.3'

In [162]:
int('23') + float('2.3')

25.3

In [1]:
x = 12
int(str(x) + '0')

120

## Sequences

In [9]:
baseline_high = 14.48
highs_list = [baseline_high - 0.880, baseline_high - 0.093,
              baseline_high + 0.105, baseline_high + 0.684]
highs_list

[13.6, 14.387, 14.585, 15.164]

In [10]:
sum(highs_list)/len(highs_list)

14.434000000000001

In [11]:
baseline_low = 3.00
lows_tuple = (baseline_low - 0.872, baseline_low - 0.629,
              baseline_low - 0.126, baseline_low + 0.728)
lows_tuple

(2.128, 2.371, 2.874, 3.7279999999999998)

## Arrays

In [12]:
import numpy as np

In [13]:
highs = np.array(highs_list)

In [14]:
lows = np.array((baseline_low - 0.872, baseline_low - 0.629,
                 baseline_low - 0.126, baseline_low + 0.728))

In [15]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [16]:
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [17]:
print(highs)

[ 13.6    14.387  14.585  15.164]


In [18]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [19]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

In [20]:
(9/5) * (highs - lows) + 32

array([ 52.6496,  53.6288,  53.0798,  52.5848])

In [21]:
highs.size

4

In [22]:
highs.mean()

14.434000000000001

In [23]:
np.mean(highs)

14.434000000000001

In [30]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [24]:
highs.item(0)

13.6

In [25]:
highs.item(1)

14.387

In [29]:
highs.item(-1)

15.164

In [31]:
highs.item(1) - highs.item(0)

0.7870000000000008

In [32]:
np.diff(highs)

array([ 0.787,  0.198,  0.579])

## Ranges

In [35]:
by_four = np.arange(1, 1000000, 4)
by_four

array([     1,      5,      9, ..., 999989, 999993, 999997])

In [37]:
4 * sum( 1/by_four - 1/(by_four + 2) )

3.1415906535898936

### Birthday problem

In [38]:
all_different = (364/365)*(363/365)*(362/365)

In [39]:
1 - all_different

0.016355912466550215

In [40]:
k = 4
numerators = np.arange(364, 365-k, -1)
numerators

array([364, 363, 362])

In [41]:
1 - np.prod(numerators/365)

0.016355912466550215

In [42]:
k = 40
numerators = np.arange(364, 365-k, -1)
1 - np.prod(numerators/365)

0.89123180981794903

In [43]:
ten = np.arange(1, 9)
np.cumprod(ten)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])

In [44]:
numerators = np.arange(364, 0, -1)
chances = 1 - np.cumprod(numerators/365)
chances.item(40-2)

0.891231809817949