In [1]:
import numpy as np
np.set_printoptions(threshold=50, linewidth=50)

In [2]:
# From Lecture 6
from datascience import *
full = Table.read_table('NC-EST2014-AGESEX-RES.csv')
partial = full.select(['SEX', 'AGE', 4, 8])
simple = partial.relabeled(2, '2010').relabeled(3, '2014')
census = simple.with_columns([
        'Change', simple.column('2014')-simple.column('2010'),
        'Growth', (simple.column('2014')/simple.column('2010')) ** (1/4) - 1
    ])
census.set_format('Growth', PercentFormatter)
census.set_format([2, 3, 4], NumberFormatter)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 0    | 3,951,330   | 3,948,350   | -2,980    | -0.02%
0    | 1    | 3,957,888   | 3,962,123   | 4,235     | 0.03%
0    | 2    | 4,090,862   | 3,957,772   | -133,090  | -0.82%
0    | 3    | 4,111,920   | 4,005,190   | -106,730  | -0.66%
0    | 4    | 4,077,552   | 4,003,448   | -74,104   | -0.46%
0    | 5    | 4,064,653   | 4,004,858   | -59,795   | -0.37%
0    | 6    | 4,073,013   | 4,134,352   | 61,339    | 0.37%
0    | 7    | 4,043,047   | 4,154,000   | 110,953   | 0.68%
0    | 8    | 4,025,604   | 4,119,524   | 93,920    | 0.58%
0    | 9    | 4,125,415   | 4,106,832   | -18,583   | -0.11%
... (296 rows omitted)

In [3]:
males = census.where('SEX', 1)
females = census.where('SEX', 2)

In [4]:
females

SEX  | AGE  | 2010        | 2014        | Change    | Growth
2    | 0    | 1,932,910   | 1,930,493   | -2,417    | -0.03%
2    | 1    | 1,937,556   | 1,938,870   | 1,314     | 0.02%
2    | 2    | 2,002,177   | 1,935,270   | -66,907   | -0.85%
2    | 3    | 2,010,648   | 1,956,572   | -54,076   | -0.68%
2    | 4    | 1,993,240   | 1,959,950   | -33,290   | -0.42%
2    | 5    | 1,988,080   | 1,961,391   | -26,689   | -0.34%
2    | 6    | 1,993,603   | 2,024,024   | 30,421    | 0.38%
2    | 7    | 1,979,908   | 2,031,760   | 51,852    | 0.65%
2    | 8    | 1,971,142   | 2,014,402   | 43,260    | 0.54%
2    | 9    | 2,018,378   | 2,009,560   | -8,818    | -0.11%
... (92 rows omitted)

#### Discussion question

In [5]:
females.sort('2014', descending=True).column('AGE').item(1)

54

In [6]:
males.sort('2014', descending=True)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
1    | 999  | 152,089,484 | 156,936,487 | 4,847,003 | 0.79%
1    | 23   | 2,151,095   | 2,399,883   | 248,788   | 2.77%
1    | 24   | 2,161,380   | 2,391,398   | 230,018   | 2.56%
1    | 22   | 2,188,228   | 2,367,842   | 179,614   | 1.99%
1    | 21   | 2,241,095   | 2,310,734   | 69,639    | 0.77%
1    | 25   | 2,177,171   | 2,295,836   | 118,665   | 1.34%
1    | 20   | 2,331,846   | 2,269,570   | -62,276   | -0.67%
1    | 54   | 2,091,677   | 2,242,828   | 151,151   | 1.76%
1    | 26   | 2,102,375   | 2,240,026   | 137,651   | 1.60%
1    | 19   | 2,334,906   | 2,220,790   | -114,116  | -1.24%
... (92 rows omitted)

In [7]:
males.where(males.column('Change') > 300000).sort('AGE').show()

In [8]:
males.where(np.logical_and(males.column('AGE') > 55, 
                           males.column('AGE') < 70)).show()

In [9]:
census.where(np.logical_or(census.column('AGE') == 18,
                           census.column('AGE') == 19))

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 18   | 4,491,005   | 4,225,590   | -265,415  | -1.51%
0    | 19   | 4,571,385   | 4,326,394   | -244,991  | -1.37%
1    | 18   | 2,305,733   | 2,165,062   | -140,671  | -1.56%
1    | 19   | 2,334,906   | 2,220,790   | -114,116  | -1.24%
2    | 18   | 2,185,272   | 2,060,528   | -124,744  | -1.46%
2    | 19   | 2,236,479   | 2,105,604   | -130,875  | -1.50%

## Functions

In [10]:
def percent(x):
    return round(100*x, 2)

In [11]:
percent(1/6)

16.67

In [12]:
sixth = 1/6
percent(sixth)

16.67

In [13]:
percent(1/6000)

0.02

In [14]:
percent(1/60000)

0.0

In [15]:
def percent(x):
    if x < 0.00005:
        return 100 * x
    return round(100 * x, 2)

In [16]:
print('1/6 =', percent(1/6))
print('1/6000 =', percent(1/6000))
print('1/60000 =', percent(1/60000))

1/6 = 16.67
1/6000 = 0.02
1/60000 = 0.0016666666666666668


In [17]:
print('1/60000000000 =', percent(1/60000000000))

1/60000000000 = 1.6666666666666667e-09


In [18]:
def percent(x):
    if x < 1e-8:
        return 0.0
    elif x < 0.00005:
        return 100 * x
    else:
        return round(100 * x, 2)

In [19]:
print('1/6 =', percent(1/6))
print('1/6000 =', percent(1/6000))
print('1/60000 =', percent(1/60000))
print('1/60000000000 =', percent(1/60000000000))

1/6 = 16.67
1/6000 = 0.02
1/60000 = 0.0016666666666666668
1/60000000000 = 0.0


In [20]:
percent(-1/6)

0.0

In [21]:
-1/6 < 1e-8

True

In [22]:
def percent(x):
    if abs(x) < 1e-8:
        return 0.0
    elif abs(x) < 0.00005:
        return 100 * x
    else:
        return round(100 * x, 2)

In [23]:
print('1/6 =', percent(1/6))
print('1/6000 =', percent(1/6000))
print('1/60000 =', percent(1/60000))
print('1/60000000000 =', percent(1/60000000000))
print('-1/6 =', percent(-1/6))

1/6 = 16.67
1/6000 = 0.02
1/60000 = 0.0016666666666666668
1/60000000000 = 0.0
-1/6 = -16.67


In [24]:
census.where(np.logical_or(census.column('AGE') == 18,
                           census.column('AGE') == 19))

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 18   | 4,491,005   | 4,225,590   | -265,415  | -1.51%
0    | 19   | 4,571,385   | 4,326,394   | -244,991  | -1.37%
1    | 18   | 2,305,733   | 2,165,062   | -140,671  | -1.56%
1    | 19   | 2,334,906   | 2,220,790   | -114,116  | -1.24%
2    | 18   | 2,185,272   | 2,060,528   | -124,744  | -1.46%
2    | 19   | 2,236,479   | 2,105,604   | -130,875  | -1.50%

In [25]:
def voting_teens(t):
    return t.where(np.logical_or(t.column('AGE') == 18, t.column('AGE') == 19))

In [26]:
voting_teens(females)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
2    | 18   | 2,185,272   | 2,060,528   | -124,744  | -1.46%
2    | 19   | 2,236,479   | 2,105,604   | -130,875  | -1.50%

In [27]:
voting_teens(males)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
1    | 18   | 2,305,733   | 2,165,062   | -140,671  | -1.56%
1    | 19   | 2,334,906   | 2,220,790   | -114,116  | -1.24%

In [28]:
voting_teens(census)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 18   | 4,491,005   | 4,225,590   | -265,415  | -1.51%
0    | 19   | 4,571,385   | 4,326,394   | -244,991  | -1.37%
1    | 18   | 2,305,733   | 2,165,062   | -140,671  | -1.56%
1    | 19   | 2,334,906   | 2,220,790   | -114,116  | -1.24%
2    | 18   | 2,185,272   | 2,060,528   | -124,744  | -1.46%
2    | 19   | 2,236,479   | 2,105,604   | -130,875  | -1.50%

In [29]:
voting_teens(census).column('Growth')

array([-0.01511402, -0.01367608, -0.01561422,
       -0.01244902, -0.01458707, -0.01496204])

#### Discussion Question

In [30]:
def f(s):
    return np.round(s / sum(s) * 100, 2)

In [31]:
f(np.array([1, 1, 3, 1, 2]))

array([ 12.5,  12.5,  37.5,  12.5,  25. ])

In [32]:
f(females.where(females.column('AGE') < 5).column('2014'))

array([ 19.86,  19.94,  19.91,  20.13,  20.16])

In [33]:
voting_teens(census).apply(percent, 'Growth')

array([-1.51, -1.37, -1.56, -1.24, -1.46, -1.5 ])

In [34]:
def mf(code):
    if code == 0:
        return 'Total'
    elif code == 1:
        return 'Male'
    elif code == 2:
        return 'Female'
census_mf = census.with_column('SEX', census.apply(mf, 'SEX'))
census_mf.show()

## Pivot

In [35]:
pivoted = census_mf.relabeled('2014', 'Population').pivot('SEX', 'AGE', 'Population', sum)
fraction = pivoted.with_column('Fraction', pivoted.column(2)/pivoted.column(3))
fraction.set_format('Fraction', PercentFormatter).show()

In [36]:
decade = census_mf.with_column('Nearest Decade', np.round(census.column('AGE'), -1))
decade

SEX   | AGE  | 2010        | 2014        | Change    | Growth | Nearest Decade
Total | 0    | 3,951,330   | 3,948,350   | -2,980    | -0.02% | 0
Total | 1    | 3,957,888   | 3,962,123   | 4,235     | 0.03%  | 0
Total | 2    | 4,090,862   | 3,957,772   | -133,090  | -0.82% | 0
Total | 3    | 4,111,920   | 4,005,190   | -106,730  | -0.66% | 0
Total | 4    | 4,077,552   | 4,003,448   | -74,104   | -0.46% | 0
Total | 5    | 4,064,653   | 4,004,858   | -59,795   | -0.37% | 0
Total | 6    | 4,073,013   | 4,134,352   | 61,339    | 0.37%  | 10
Total | 7    | 4,043,047   | 4,154,000   | 110,953   | 0.68%  | 10
Total | 8    | 4,025,604   | 4,119,524   | 93,920    | 0.58%  | 10
Total | 9    | 4,125,415   | 4,106,832   | -18,583   | -0.11% | 10
... (296 rows omitted)

In [37]:
pivoted = decade.relabeled('2014', 'Population').pivot('SEX', 'Nearest Decade', 'Population', sum)
fraction = pivoted.with_column('Fraction', pivoted.column(2)/pivoted.column(3))
fraction.set_format('Fraction', PercentFormatter).show()

## Group

In [38]:
cardio = Table.read_table("~/Downloads/Data 8 Cardio Participation Log (Responses) - Form Responses 1.csv")
cardio

Timestamp          | On what day did you attend? | How many laps did you complete? | In how many minutes? | How tired were you at the end? | What's your identifier?
1/20/2016 22:05:05 | Thursday, 1/21              | 5                               | 14                   | 4                              | blue running shoes with black black pants.
1/21/2016 8:07:05  | Thursday, 1/21              | 22                              | 30                   | 3                              | Cal lights>WIRAs
1/21/2016 8:23:16  | Thursday, 1/21              | 6                               | 18                   | 6                              | Ontario
1/21/2016 8:36:59  | Thursday, 1/21              | 8                               | 20                   | 5                              | Smooth Criminal
1/21/2016 8:37:28  | Thursday, 1/21              | 8                               | 20                   | 5                              | Tomato
1/21/2016 9:02:25  | Thursday, 1/21              | 5.5                             | 25                   | 5                              | SS
1/21/2016 9:07:08  | Thursday, 1/21              | 12                              | 35                   | 4                              | astennet
1/21/2016 9:21:12  | Thursday, 1/21              | 8                               | 35                   | 3                              | BR
1/21/2016 9:29:18  | Thursday, 1/21              | 6                               | 30                   | 5                              | TrueLoveInAGraph
1/21/2016 9:38:18  | Thursday, 1/21              | 5                               | 11                   | 3                              | Edward Snowden
... (16 rows omitted)

In [39]:
days = cardio.select([1, 2, 3]).group(0, sum)
days

On what day did you attend? | How many laps did you complete? sum | In how many minutes? sum
Thursday, 1/21              | 131                                 | 394
Thursday, 1/28              | 99                                  | 265.5

In [40]:
days.with_column('Minutes/Lap', days.column(2)/days.column(1))

On what day did you attend? | How many laps did you complete? sum | In how many minutes? sum | Minutes/Lap
Thursday, 1/21              | 131                                 | 394                      | 3.00763
Thursday, 1/28              | 99                                  | 265.5                    | 2.68182